# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Ruff - Python linter and formatter (extremely fast)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      # Run the linter
      - id: ruff-check
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # Black - Python code formatter
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3

  # Mypy - Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies: [
          mypy,
          types-requests,
          types-PyYAML,
          torch,
          transformers
        ]
        args: [--ignore-missing-imports, --no-strict-optional]

  # Additional useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Check for merge conflicts
      - id: check-merge-conflict
      # Check YAML syntax
      - id: check-yaml
      # Check TOML syntax
      - id: check-toml
      # Remove trailing whitespace
      - id: trailing-whitespace
      # Ensure files end with newline
      - id: end-of-file-fixer
      # Check for large files
      - id: check-added-large-files
        args: ['--maxkb=1000']
